version: '3.7'

services:

  backend:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    ports:
      - 5432:5432

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - 3000:80
    depends_on:
      - backend

  # client_dev:
  #   container_name: client_dev
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   volumes:
  #     - './client:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   tty: true


volumes:
  postgres_data: