# Generated by Django 3.0.5 on 2020-04-18 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=10)),
                ('mass', models.CharField(max_length=10)),
                ('hair_color', models.CharField(max_length=20)),
                ('skin_color', models.CharField(max_length=20)),
                ('eye_color', models.CharField(max_length=20)),
                ('birth_year', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=20)),
                ('homeworld', models.CharField(max_length=25)),
                ('person_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.PersonCollection')),
            ],
        ),
    ]
