# Generated by Django 3.0.5 on 2020-04-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_person_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date',
        ),
    ]
