# Generated by Django 3.0.5 on 2020-04-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_remove_person_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='personcollection',
            name='last_successful_fetch_page',
            field=models.IntegerField(default=1),
        ),
    ]
