# Generated by Django 3.0.5 on 2020-04-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20200419_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='personcollection',
            name='data_fetch_complete',
            field=models.BooleanField(default=False),
        ),
    ]
