# Generated by Django 3.0.5 on 2020-04-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_personcollection_data_fetch_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
