# Generated by Django 3.0.5 on 2020-04-20 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_person_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcollection',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
