# Generated by Django 3.0.5 on 2020-04-20 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_auto_20200420_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcollection',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 20, 7, 58, 14, 806825, tzinfo=utc)),
        ),
    ]
